### PR TITLE
Explain core binding mechanism

### LINKED ISSUE #252: Mention that a binding is mandatory for a TD to exist
Coming from https://github.com/w3c/wot-binding-templates/issues/238#issuecomment-1431640818

### LINKED ISSUE #255: A diagram to help understand what is happening in operation mappings.

### PR DESCRIPTION
**Pull request by egekorkan**
fixes #255 and starts addressing #238
fixes #252

[Netlify Preview](https://deploy-preview-262--wot-binding-templates.netlify.app/)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/pull/262.html" title="Last updated on Mar 22, 2023, 9:09 AM UTC (3210590)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/262/6e03f10...3210590.html" title="Last updated on Mar 22, 2023, 9:09 AM UTC (3210590)">Diff</a>

### CODE REVIEW

**Comment by egekorkan** [comment]
Call of 15.03:
- Overall the diagram is good
- An SVG version would be better to avoid the resolution problem
- It would be good to have a sequence diagram with protocol requests for each protocol binding
- A sentence before the diagram to explain the application logic would be nice (here it would be, "this is how a message sequence would look like if the Consumer wants the robot to move to x:12 and y:100". However, it would be better take one of the existing use cases (e.g. air conditioner)

**Comment by danielpeintner** [comment]
> * An SVG version would be better to avoid the resolution problem.

I agree with using SVG.
I just wonder why in the current TD document we use PNG instead of the SVG counterpart (they exist in most of the cases). Shall we open another issue/PR to change that also?

**Comment by egekorkan** [comment]
> I just wonder why in the current TD document we use PNG instead of the SVG counterpart

I am not 100% sure but SVG is not the best when it comes to text representation. The automatically generated SVGs are converted to PNGs at some point.

**Comment by egekorkan** [comment]
I have taken all the feedback from the last call and everything looks nicer now and has more explanations.

**Comment by danielpeintner** [comment]
I noticed you are using quotes for JSON terms now 👍
I also noticed that for `"input": { x: ..., y: ...}` you are not doing that. Just an oversight?

**Comment by egekorkan** [comment]
@danielpeintner it was definitely an oversight, I have changed it now.

**Comment by danielpeintner** [comment]
> I have changed it now.

I think you missed to update the PNG version. Anyhow, didn't we want to remove PNG anyway?

**Comment by egekorkan** [comment]
> > I have changed it now.
> 
> I think you missed to update the PNG version. Anyhow, didn't we want to remove PNG anyway?

Good catch. I have removed the old and did the same with the other figure we have.

**Review by relu91 — APPROVED** [review]

**Comment by egekorkan** [comment]
Call of 22.03: No objections, merging

**Pull request merged**
