### PR TITLE
update dataSchema elements

### PR DESCRIPTION
**Pull request by mjkoster**
change inputData, outputData to dataSchema using "schema",
"inputSchema", outputSchema" keywords and update descriptive text

### CODE REVIEW

**Comment by zolkis** [comment]
Looks good.

**Comment by vcharpenay** [comment]
when you write `dataSchema`, is it a reference to the [`DataSchema` type](https://w3c.github.io/wot-thing-description/#dataschema) in the TD spec? If it indeed is, would it be possible to write it with a capital 'D' and within `<code></code>` tags?

**Comment by mjkoster** [comment]
updated DataSchema, float=> number, removed undefined interaction types e.g. cancelAction

**Comment by mkovatsc** [comment]
Was closing intentional?

**Comment by mjkoster** [comment]
I couldn't figure out how to resolve the conflicts locally, then I did. I reopened the PR and it can now be merged

**Comment by mjkoster** [comment]
Ready to merge #31

**Comment by sebastiankb** [comment]
perfect, thanks!

**Pull request merged**
