### PR TITLE
WIP: Updating to new TD spec and definitions

### PR DESCRIPTION
**Pull request by egekorkan**
These are the commits that correspond to updating the protocol binding to the CR version of the TD and Architecture specs

### CODE REVIEW

**Comment by egekorkan** [comment]
@mjkoster could you check if this PR is OK? Here is a rendered version: https://cdn.statically.io/gh/w3c/wot-binding-templates/korkan-update/index.html

**Comment by mjkoster** [comment]
Yes, it looks good. 

Thanks!

Michael

**Comment by mjkoster** [comment]
One more comment, in the CoAP and MQTT binding discussion, I would change "fictitious" to "unofficial" at some point.

**Comment by egekorkan** [comment]
Regarding fictitious comment, I have copied it from TD spec so I would bring the discussion over ^^

**Pull request merged**
