### PR TITLE
Update examples based on TD spec

### PR DESCRIPTION
**Pull request by yamagile**
* Add writable and observable to Property
* Update float -> number based on JSON schema

* Move out 2.2.4 and 2.2.5 based on the call on 23 Jan 2018

* Some typos fixed

### CODE REVIEW

**Comment by vcharpenay** [comment]
Note: the value for `item` must be an object, not an array (see for instance [this example](http://json-schema.org/example2.html#the-entry-schema---adding-constraints)).

Example 6 would become (note the `anyOf` keyword to define a logical OR of various schemas):
```
{
  "inputData": {
    "type": "array",
    "item": {
      "anyOf": [
          {
            "type": "object",
            "field": [
              {
                "name": "bn",
                "type": "string",
                "const": "example/light"
              }
            ]
          },
          {
            "type": "object",
            "field": [
              {
                "name": "n",
                "type": "string",
                "const": "level"
              },
              {
                "name": "v",
                "@type": ["sch:levelvalue"],
                "type": "integer",
                "minimum": 0,
                "maximum": 255
              }
            ]
          },
          {
            "type": "object",
            "field": [
              {
                "name": "n",
                "type": "string",
                "const": "time"
              },
              {
                "name": "v",
                "@type": ["sch:ramptimevalue"],
                "type": "integer",
                "minimum": 0,
                "maximum": 65535
              }
            ]
          }
        ]
    }
  }
}
```

And example 7:
```
{
  "inputData": {
    "type": "array",
    "item": {
        "type": "object",
        "fields": [
          {
            "name": "href",
            "type": "string",
            "const": "/light/level"
          },
          {
            "name": "rep",
            "type": "object",
            "field": [
              {
                "name": "dimming",
                "@type": ["sch:levelvalue"],
                "type": "integer",
                "minimum": 0,
                "maximum": 255
              }
            ]
          }
      },
      {
        "type": "object",
        "field": [
          {
            "name": "href",
            "type": "string",
            "const": "/light/time"
          },
          {
            "name": "rep",
            "type": "object",
            "field": [
              {
                "name": "ramptime",
                "@type": ["sch:ramptimevalue"],
                "type":"integer",
                "minimum": 0,
                "maximum": 65535
              }
            ]
          }
        ]
      }
    ]
  }
}
```

**Comment by yamagile** [comment]
I updated this PR based on the call on 13 Feb 2018. Would someone check and merge?

**Comment by mkovatsc** [comment]
Merging as discussed in the Editor's call on 28 Feb 2018.
@mjkoster will align his PR #31 in case of conflicts.

**Comment by yamagile** [comment]
@mkovatsc  @mjkoster TY

**Comment by mjkoster** [comment]
I can't do the resolve of PR 31 because I don't have write access. However, if we just accept all incoming changes, the only thing that gets clobbered is the change to "item" in Victor's note, which I will re-apply. I will also fix the http vocabulary issue after we get the merge conflicts resolved.

**Pull request merged**
