### PR TITLE
Specifying terms influenced by different bindings

### LINKED ISSUE #218: Specifying what TD terms are specified by different binding templates
Currently, we specify what each binding template needs to provide. However, we are not putting the relationships to the TD terms clearly. There are some explanations at https://w3c.github.io/wot-architecture/#sec-hypermedia-controls but we can be more explicit here. From initial thinking, the relationships should be:
- Protocols: Everything inside a form can be specified but the `contentType` is not necessarily part of it.
- Payloads: Everything inside the form except header and protocol specific terms, and data schema
- Platforms: Combination of the two above

### PR DESCRIPTION
**Pull request by egekorkan**
fixes #218

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/pull/263.html" title="Last updated on Mar 22, 2023, 3:13 PM UTC (ea9df23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/263/6e03f10...ea9df23.html" title="Last updated on Mar 22, 2023, 3:13 PM UTC (ea9df23)">Diff</a>

### CODE REVIEW

**Comment by egekorkan** [comment]
Call of 15.03:
- How to validate the URI Scheme Usage: See (https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#abnf , https://github.com/w3c/wot-binding-templates/issues/245). 
- ABNF parsers in Consumer would be too much but for implementors would be good.
- We need to explain how Consumers should identify the protocol from the URI.
- Term and keyword are used interchangeably
- Assignment should be changed to something like "Subspecification MUST specify"

**Comment by egekorkan** [comment]
@danielpeintner you had mentioned that "Assignment" was confusing. I have changed it now to `Specification Requirement` and added a sentence that explains these.

**Comment by relu91** [comment]
@egekorkan is this ready to review or do you need to close the points defined in https://github.com/w3c/wot-binding-templates/pull/263#issuecomment-1470244570

**Comment by egekorkan** [comment]
> @egekorkan is this ready to review or do you need to close the points defined in [#263 (comment)](https://github.com/w3c/wot-binding-templates/pull/263#issuecomment-1470244570) ?

It is ready to review. How to pick the correct binding via the URI scheme needs another PR

**Comment by egekorkan** [comment]
Call of 22.03, no objections, merging.

**Pull request merged**
