### PR TITLE
Various fixes to the issues

### PR DESCRIPTION
**Pull request by egekorkan**
Included issues:
+ #55 
+ #60 
+ #54 
+ #63 
+ #56

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/pull/71.html" title="Last updated on Aug 30, 2019, 7:46 AM UTC (b483145)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/71/f631f2e...b483145.html" title="Last updated on Aug 30, 2019, 7:46 AM UTC (b483145)">Diff</a>

### CODE REVIEW

**Comment by takuki** [comment]
Section **Object Definition to XML Schema** contains Example 9, 10 and 11.

Example 9 is for object. On the other hand, example 10 and 11 are for arrays.
The content for example 10 and 11 needs to be copied from [here](https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/#object-definition-to-xml-schema).

For arrays, it needs a dedicated subsection **Array Definition to XML Schema**.
See [here](https://www.w3.org/TR/2018/WD-wot-thing-description-20180405/#array-definition-to-xml-schema).

**Comment by egekorkan** [comment]
@takuki the mixing issue you mentioned is fixed now, thank you for reviewing!

**Comment by egekorkan** [comment]
@takuki or @mjkoster could you please review this PR? Thanks !

**Comment by egekorkan** [comment]
I have addressed all the comments for the issues mentioned in this PR

**Pull request merged**
