### PR TITLE
Publication Prep

### PR DESCRIPTION
**Pull request by egekorkan**
I have done the following:

- Copied https://github.com/w3c/wot-thing-description/blob/main/publication/ver11/4-wd/README.md as indicated by #289
- Beautified the file, updated the links accordingly, added the commands, made it more instructive
- generated static.html, tidied up with HTML Tidy to generate Overview.html

Validation results (No need to manually update):
- [Link Checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fdeploy-preview-290--wot-binding-templates.netlify.app%2Fpublication%2Fnote3%2Foverview&hide_type=all&depth=&check=Check) - No errors (it shows an error for this Note's link)
- [Pubrules Checker](https://www.w3.org/pubrules/?url=https%3A%2F%2Fdeploy-preview-290--wot-binding-templates.netlify.app%2Fpublication%2Fnote3%2Foverview&profile=NOTE&validation=simple-validation&informativeOnly=true&echidnaReady=false&patentPolicy=pp2020): Errors exist but they can be ignored.
  - There are some errors from Netlify that can be ignored.
  - The center error from the HTML Validator is also here. It can be ignored.
- [CSS Checker](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fdeploy%2Dpreview%2D290%2D%2Dwot%2Dbinding%2Dtemplates.netlify.app%2Fpublication%2Fnote3%2Foverview) - No errors
- [HTML Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-290--wot-binding-templates.netlify.app%2Fpublication%2Fnote3%2Foverview) - There is an error about using `<center>` but this is coming from Netlify and can be ignored.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/pull/290.html" title="Last updated on May 31, 2023, 2:41 PM UTC (3563204)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-binding-templates/290/605149d...3563204.html" title="Last updated on May 31, 2023, 2:41 PM UTC (3563204)">Diff</a>

### CODE REVIEW

**Comment by egekorkan** [comment]
The github version can be used for the pubrules check: https://raw.githubusercontent.com/w3c/wot-binding-templates/7d8d26e98a5157c306addfa140ed7933ff54c894/publication/note3/Overview.html

**Comment by egekorkan** [comment]
Pubrules error: [EXCEPTION] The document "Web of Things (WoT) Binding Templates" seems to be an Editor's Draft, which is not supported.

It is not clear from previous instructions on what needs to be changed to move from ED to Note

**Comment by egekorkan** [comment]
Call of 24.05: 
- The respec parameter should be changed to "Note" from "ED" and the process should be done again.
- Document the HTML Tidy commands to write to the Overview.html file

**Comment by egekorkan** [comment]
All the checks except some CSS that is generated by respec are passing. @danielpeintner did you have the same issue in Scripting API? You can find them at the [CSS validator](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fdeploy-preview-290--wot-binding-templates.netlify.app%2Fpublication%2Fnote3%2Foverview) or in [the HTML validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdeploy-preview-290--wot-binding-templates.netlify.app%2Fpublication%2Fnote3%2Foverview) of W3C.

**Comment by danielpeintner** [comment]
> @danielpeintner did you have the same issue in Scripting API?

We did run into some other ReSpec issues, see https://github.com/w3c/wot-scripting-api/issues/480

**Comment by egekorkan** [comment]
OK so I checked where the error comes from and it is not due to respec, also not the errors like in @danielpeintner case above. The static HTML generated from respec is correct but HTML tidy adds errors.

[CSS validation of static.html](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fdeploy-preview-290--wot-binding-templates.netlify.app%2Fpublication%2Fnote3%2Fstatic&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en)

**Comment by egekorkan** [comment]
The addition of CDATA seems to be a bug that others counter (see [here](https://github.com/htacg/tidy-html5/issues/660)). I will go around this issue for now.

**Pull request merged**
